import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        
        <title>João Vitor A. Smerecki.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          
      

      <main className={styles.main}>
            <video loop autoPlay muted className= {styles.videofundo}>
              <source  src='/video-fundo.webm' type='video/webm'/>
            </video> 
            
  
      <div className={styles.image}/>
        <h1 className={styles.title}>``
          João Vitor A. Smerecki.
        </h1>

        <p className={styles.description}>
          Motion Designer e estudante de Engenharia de Software.
        </p>

        <div className={styles.grid}>
          <a 
            href="https://vimeo.com/user172868514" 
            className={styles.card}
            target="_blank" rel="noopener noreferrer"
          >
            <h2>Portifólio &rarr;</h2>
            <p>Veja alguns dos meus trabalhos como Motion Designer.</p>
          </a>

          <a
            href="https://www.linkedin.com/in/jo%C3%A3o-vitor-alves-smerecki-81a56b237/" 
            className={styles.card}
            target="_blank" rel="noopener noreferrer"
          >
            <h2>Linkedin &rarr;</h2>
            <p>conheça um pouco mais sobre mim.</p>
          </a>

          <a
            href="https://api.whatsapp.com/send?phone=5565999315855&text=Ol%C3%A1%2C%20gostaria%20de%20realizar%20um%20or%C3%A7amento."
            className={styles.card}
            target="_blank" rel="noopener noreferrer"
          >
            <h2>Meu Whatsapp &rarr;</h2>
            <p>Entre em contato comigo.  </p>
          </a>

          <a
            href=""
            className={styles.card}
            target="_blank" rel="noopener noreferrer"
          >
            <h2>Sobre mim &rarr;</h2>
            <p>
              Aqui falo um pouco sobre minha trajetória.
            </p>
          </a>
        </div>
        
      </main>

    </div>
  )
}

export default Home
